tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary": "#001239",
                "on-tertiary-fixed-variant": "#304578",
                "tertiary-fixed": "#dae2ff",
                "surface-container-high": "#e9e7ef",
                "surface-tint": "#4459ab",
                "primary-container": "#001f73",
                "on-tertiary-fixed": "#001946",
                "inverse-surface": "#2f3036",
                "outline": "#757683",
                "secondary-fixed": "#AFC4FF",
                "on-secondary-fixed": "#00164e",
                "on-primary-container": "#778be1",
                "primary-fixed-dim": "#b8c4ff",
                "surface-dim": "#dbd9e1",
                "on-primary-fixed": "#001453",
                "on-tertiary-container": "#7a8fc7",
                "on-surface-variant": "#454651",
                "surface-container": "#efedf5",
                "error-container": "#ffdad6",
                "on-background": "#1a1b21",
                "on-error": "#ffffff",
                "primary": "#001f73",
                "secondary-fixed-dim": "#b5c4ff",
                "on-secondary-container": "#223c88",
                "on-secondary": "#ffffff",
                "on-secondary-fixed-variant": "#29428d",
                "surface-variant": "#e3e1e9",
                "background": "#F5F5F5",
                "surface-container-lowest": "#ffffff",
                "secondary": "#6F86D6",
                "outline-variant": "#c5c5d3",
                "surface-container-low": "#f4f2fa",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "surface": "#F5F5F5",
                "tertiary-container": "#0e2758",
                "tertiary-fixed-dim": "#b1c5ff",
                "secondary-container": "#AFC4FF",
                "on-tertiary": "#ffffff",
                "surface-bright": "#F5F5F5",
                "error": "#ba1a1a",
                "brand-yellow": "#F5C000"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "container-max": "1280px",
                "margin-mobile": "20px",
                "margin-desktop": "64px",
                "gutter": "24px",
                "unit": "8px",
                "section-gap": "80px",
                "stack-sm": "8px",
                "stack-md": "16px",
                "stack-lg": "32px"
            },
            "fontFamily": {
                "label-bold": ["Inter"],
                "label-sm": ["Inter"],
                "display-lg": ["Inter"],
                "headline-md": ["Inter"],
                "headline-sm": ["Inter"],
                "display-lg-mobile": ["Inter"],
                "body-lg": ["Inter"],
                "body-md": ["Inter"],
                "button-text": ["Inter"]
            },
            "fontSize": {
                "label-bold": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-md": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display-lg-mobile": ["36px", { "lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "button-text": ["16px", { "lineHeight": "16px", "fontWeight": "600" }]
            }
        },
    },
}
